import { ArrowLeft, Loader2, MessageCircleQuestion, Send } from "lucide-react";
import React, { useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { TopicRssStoryCard } from "@/components/TopicRssStoryCard";
import { trpc } from "@/lib/trpc";

const relativeTime = (value: Date | string) => new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });

export default function TopicDiscussion() {
  const auth = useAuth(); const utils = trpc.useUtils(); const [, params] = useRoute("/topics/:slug/discussion/:kind/:entryId"); const slug = params?.slug ?? ""; const kind = params?.kind === "thread" ? "thread" : "post"; const entryId = Number(params?.entryId); const [body, setBody] = useState("");
  const discussion = trpc.topicCommunity.discussion.useQuery({ slug, kind, entryId }, { enabled: auth.isAuthenticated && Boolean(slug) && Number.isFinite(entryId) });
  const replyThread = trpc.topicCommunity.reply.useMutation({ onSuccess: async () => { setBody(""); await utils.topicCommunity.discussion.invalidate({ slug, kind, entryId }); }, onError: e => toast.error(e.message) });
  const replyPost = trpc.topicCommunity.replyToPost.useMutation({ onSuccess: async () => { setBody(""); await utils.topicCommunity.discussion.invalidate({ slug, kind, entryId }); }, onError: e => toast.error(e.message) });
  if (auth.loading || discussion.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f8fa]"><Loader2 className="h-6 w-6 animate-spin text-[#635bff]" /></div>;
  if (!discussion.data) return <main className="grid min-h-screen place-items-center bg-[#f7f8fa] p-6 text-center"><div><h1 className="text-2xl font-semibold">Discussion unavailable</h1><Link href={`/topics/${slug}`} className="mt-4 inline-block text-sm font-semibold text-[#635bff]">Return to topic</Link></div></main>;
  const { community, entry, replies, isMember } = discussion.data;
  const story = kind === "thread" ? (entry as { story?: { title: string; link: string; description: string | null; thumbnailUrl: string | null; videoUrl: string | null; videoMimeType: string | null; publishedAt: Date | string | null } }).story : undefined;
  const send = () => kind === "thread" ? replyThread.mutate({ threadId: entryId, body }) : replyPost.mutate({ postId: entryId, body });
  return <div className="min-h-screen bg-[#f7f8fa] text-[#14161a]"><header className="flex h-[76px] items-center border-b border-[#e6e8ed] bg-[#f7f8fa]/90 px-5 backdrop-blur-xl sm:px-8"><Link href={`/topics/${slug}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#68707d] hover:text-[#635bff]"><ArrowLeft className="h-4 w-4" /> {community.name}</Link><div className="ml-5 min-w-0"><div className="truncate text-lg font-semibold">Discussion</div><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#8a929f]">{kind === "thread" ? "RSS Thread" : "Topic post"}</div></div></header><main className="mx-auto max-w-2xl px-5 py-8 sm:px-8"><article className="rounded-[1.5rem] border border-[#e3e6ec] bg-white p-6 shadow-[0_8px_25px_rgba(24,31,45,.03)]"><div className="text-xs font-semibold text-[#635bff]">{entry.displayName || "gvone member"} · {relativeTime(entry.createdAt)}</div>{kind === "thread" && <div className="mt-4 flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[.12em] text-[#8b7ade]"><MessageCircleQuestion className="h-3.5 w-3.5" /> Thread</div>}{story && <TopicRssStoryCard story={story} />}{entry.title && <h1 className="mt-4 text-2xl font-semibold tracking-[-.035em]">{entry.title}</h1>}<p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#68707d]">{entry.body}</p></article><section className="mt-7"><h2 className="text-xl font-semibold">Replies</h2><div className="mt-4 space-y-3">{replies.length ? replies.map((reply: any) => <article key={reply.id} className="rounded-2xl border border-[#e5e7ed] bg-white p-4"><div className="text-xs font-semibold text-[#635bff]">{reply.displayName || "gvone member"} · {relativeTime(reply.createdAt)}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#68707d]">{reply.body}</p></article>) : <div className="rounded-2xl border border-dashed border-[#d8dce4] bg-white/55 p-6 text-sm text-[#7d8794]">No replies yet. Start the discussion.</div>}</div></section>{isMember && <section className="mt-7 rounded-[1.5rem] border border-[#dcd9ff] bg-[#f8f7ff] p-5"><label htmlFor="topic-discussion-reply" className="text-sm font-semibold">Reply</label><textarea id="topic-discussion-reply" value={body} onChange={e => setBody(e.target.value)} placeholder="Share your Reply…" rows={4} className="mt-3 w-full resize-none rounded-xl border border-[#e1dfff] bg-white px-3 py-3 text-sm outline-none focus:border-[#635bff]" /><button disabled={!body.trim() || replyThread.isPending || replyPost.isPending} onClick={send} className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#635bff] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Send className="h-4 w-4" /> Send Reply</button></section>}</main></div>;
}
