import { ArrowLeft, Compass, Hash, Loader2, Plus, UsersRound } from "lucide-react";
import React, { useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

function createSlug(value: string) {
  return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 64);
}

export default function Topics() {
  const auth = useAuth();
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const [showCreator, setShowCreator] = useState(false);
  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const [description, setDescription] = useState("");
  const topics = trpc.topicCommunity.list.useQuery(undefined, { enabled: auth.isAuthenticated });
  const create = trpc.topicCommunity.create.useMutation({
    onSuccess: async (topic) => { await utils.topicCommunity.list.invalidate(); navigate(`/topics/${topic.slug}`); },
    onError: (error) => toast.error(error.message),
  });
  const join = trpc.topicCommunity.join.useMutation({
    onSuccess: async () => { toast.success("Joined topic"); await utils.topicCommunity.list.invalidate(); },
    onError: (error) => toast.error(error.message),
  });

  if (auth.loading || topics.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f8fa]"><Loader2 className="h-6 w-6 animate-spin text-[#635bff]" /></div>;
  if (!auth.isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#f7f8fa] p-6 text-center"><div><Hash className="mx-auto h-7 w-7 text-[#635bff]" /><h1 className="mt-4 text-2xl font-semibold">Sign in to discover Topics</h1><p className="mt-2 text-sm text-[#7d8794]">Topics are shared, member-created discussion communities.</p><button type="button" onClick={startLogin} className="mt-5 rounded-full bg-[#635bff] px-5 py-3 text-sm font-semibold text-white">Sign in</button></div></main>;

  return <div className="min-h-screen bg-[#f7f8fa] text-[#14161a]">
    <header className="flex h-[76px] items-center border-b border-[#e6e8ed] bg-[#f7f8fa]/90 px-5 backdrop-blur-xl sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#68707d] hover:text-[#635bff]"><ArrowLeft className="h-4 w-4" /> Reader</Link><div className="ml-5 flex min-w-0 items-center gap-2"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#17171d] text-white"><Hash className="h-4 w-4" /></span><div className="min-w-0"><div className="truncate text-lg font-semibold tracking-[-.03em]">Topics</div><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#8a929f]">Member-created communities</div></div></div><button type="button" onClick={() => setShowCreator((value) => !value)} className="ml-auto inline-flex items-center gap-2 rounded-full bg-[#635bff] px-4 py-2.5 text-sm font-semibold text-white shadow-[0_7px_18px_rgba(99,91,255,.2)]"><Plus className="h-4 w-4" /> Create topic</button></header>
    <main className="mx-auto max-w-5xl px-5 py-8 sm:px-8">
      <section className="rounded-[1.75rem] bg-[#17171d] p-6 text-white shadow-[0_16px_42px_rgba(24,24,32,.15)] sm:p-8"><div className="max-w-2xl"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-white/50"><Compass className="h-3.5 w-3.5 text-[#a7a1ff]" /> Discover communities</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">Find a place for the conversation.</h1><p className="mt-3 text-sm leading-6 text-white/60">Topics are standalone communities created by gvone members. Join a topic to start Threads, share a saved RSS story, and Reply together.</p></div></section>
      {showCreator && <section className="mt-6 rounded-[1.5rem] border border-[#dcd9ff] bg-white p-5 shadow-[0_8px_25px_rgba(24,31,45,.03)]"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Create a topic community</h2><p className="mt-1 text-sm text-[#7d8794]">Give members a clear shared subject, such as Space, AI policy, or Global affairs.</p></div><button type="button" onClick={() => setShowCreator(false)} className="text-sm font-semibold text-[#8b7ade]">Close</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold uppercase tracking-wider text-[#8a929f]">Topic name<input value={name} onChange={(event) => { setName(event.target.value); if (!slug || slug === createSlug(name)) setSlug(createSlug(event.target.value)); }} maxLength={80} placeholder="Space exploration" className="mt-2 w-full rounded-xl border border-[#e1e4ea] px-3 py-3 text-sm normal-case tracking-normal outline-none focus:border-[#635bff]" /></label><label className="text-xs font-semibold uppercase tracking-wider text-[#8a929f]">Topic address<input value={slug} onChange={(event) => setSlug(createSlug(event.target.value))} maxLength={64} placeholder="space-exploration" className="mt-2 w-full rounded-xl border border-[#e1e4ea] px-3 py-3 text-sm normal-case tracking-normal outline-none focus:border-[#635bff]" /><span className="mt-1 block normal-case tracking-normal text-[#a0a7b2]">gvone /topics/{slug || "your-topic"}</span></label></div><label className="mt-4 block text-xs font-semibold uppercase tracking-wider text-[#8a929f]">Description <span className="font-normal normal-case">(optional)</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={500} rows={3} placeholder="What belongs in this community?" className="mt-2 w-full resize-none rounded-xl border border-[#e1e4ea] px-3 py-3 text-sm normal-case leading-6 tracking-normal outline-none focus:border-[#635bff]" /></label><button type="button" disabled={!name.trim() || !slug || create.isPending} onClick={() => create.mutate({ name, slug, description: description || undefined })} className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#17171d] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{create.isPending && <Loader2 className="h-4 w-4 animate-spin" />} Create community</button></section>}
      <section className="mt-8"><div className="mb-4 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold tracking-[-.04em]">Discover Topics</h2><p className="mt-1 text-sm text-[#7d8794]">Newest activity first. Every member can browse; join to participate.</p></div><span className="rounded-full bg-[#eeedff] px-3 py-1.5 text-xs font-semibold text-[#635bff]">{topics.data?.length ?? 0} topic{(topics.data?.length ?? 0) === 1 ? "" : "s"}</span></div><div className="grid gap-4 md:grid-cols-2">{topics.data?.length ? topics.data.map((topic) => <article key={topic.id} className="rounded-[1.5rem] border border-[#e3e6ec] bg-white p-5 shadow-[0_8px_25px_rgba(24,31,45,.03)]"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f0eaff] text-[#704ee5]"><Hash className="h-4 w-4" /></span><div className="min-w-0 flex-1"><Link href={`/topics/${topic.slug}`} className="block truncate text-lg font-semibold tracking-[-.025em] hover:text-[#635bff]">{topic.name}</Link><div className="mt-1 text-xs font-semibold text-[#8b7ade]">/topics/{topic.slug}</div></div></div><p className="mt-4 min-h-10 text-sm leading-6 text-[#68707d]">{topic.description || "A member-created space for focused conversation."}</p><div className="mt-5 flex items-center justify-between gap-3 border-t border-[#f0f1f4] pt-4"><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#8a929f]"><UsersRound className="h-3.5 w-3.5" /> {topic.memberCount} member{topic.memberCount === 1 ? "" : "s"} · {topic.threadCount} Thread{topic.threadCount === 1 ? "" : "s"}</span>{topic.isMember ? <Link href={`/topics/${topic.slug}`} className="rounded-full bg-[#f2f1ff] px-3 py-2 text-xs font-semibold text-[#635bff]">Open</Link> : <button type="button" onClick={() => join.mutate({ slug: topic.slug })} disabled={join.isPending} className="rounded-full bg-[#17171d] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Join</button>}</div></article>) : <div className="col-span-full rounded-[1.5rem] border border-dashed border-[#d8dce4] bg-white/55 px-6 py-16 text-center"><Hash className="mx-auto h-7 w-7 text-[#a9a2dc]" /><h3 className="mt-4 text-lg font-semibold">No Topics yet</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#7d8794]">Create the first member community and give RSS stories a shared place to be discussed.</p><button type="button" onClick={() => setShowCreator(true)} className="mt-5 rounded-full bg-[#17171d] px-4 py-2.5 text-sm font-semibold text-white">Create a Topic</button></div>}</div></section>
    </main>
  </div>;
}
